baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Salt And Light Learning | GED Crash Course"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]